[package]

name = "mop"
version = "0.0.1"
authors = [ "Javier Fajardo <javier@fajardo.io>" ]

[dependencies]
log = "*"
env_logger = "*"
chrono = "0.4"
clap = "2"
json = "*"
xml-rs = "0.6"
id3 = { git = "https://github.com/jameshurst/rust-id3" }
curl = "*"
select = "0.4.2"
url = "*"